[package]
name = "chokurei"
version = "0.1.0"
authors = [
    "Paul Loyd <pavelko95@gmail.com>",
    "Renat <yandzeek@gmail.com>"
]

[[bin]]
name = "fetcher"
path = "src/fetcher/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[dependencies]
