[package]
name = "common"
version = "0.0.0"
publish = false

[lib]
path = "lib.rs"

[features]
commit-transaction = []

[dependencies]
log = "^0.3.7"
env_logger = "^0.4.2"
time = "^0.1.36"
url = "^1.4"
serde = "^1.0.2"
serde_derive = "^1.0.2"
